version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/coreos/dex
    steps:
      - checkout
      - run: make
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/coreos/dex
  unit_tests:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.4.12-alpine
    working_directory: /go/src/github.com/coreos/dex
    environment:
      TEST_RESULTS: /tmp/test-results
      DEX_POSTGRES_DATABASE: postgres
      DEX_POSTGRES_USER: postgres
      DEX_POSTGRES_HOST: localhost
      DEX_LDAP_TESTS: 1
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: sudo -E apt-get install -y --force-yes slapd time ldap-utils
      - run:
          name: Start LDAP
          command: sudo /etc/init.d/slapd stop
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: go get -u github.com/golang/lint/golint
      - run: make testall

  build_binary:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/coreos/dex
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make release-binary
      - run: mkdir -p _output/bin/dex && cp /go/bin/dex _output/bin/dex
      - save_cache:
          key: v1-binary-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/coreos/dex/_output/bin

  deploy_image:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/coreos/dex
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-binary-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - deploy:
          name: Install Docker client
          command: |
            set -x
            sudo curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz && sudo tar --strip-components=1 -xvzf docker-17.05.0-ce.tgz -C /usr/local/bin
      - deploy:
          name: Deploy dex Docker image
          command: |
            SHORT_SHA=$(git rev-parse --short HEAD)

            VERSION="0.1.${CIRCLE_BUILD_NUM}-${SHORT_SHA}"

            DOCKER_REPO=circleci/dex
            DOCKER_IMAGE=$DOCKER_REPO:$VERSION
            docker build -t $DOCKER_IMAGE .
            docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
            docker push $DOCKER_IMAGE
            docker push $DOCKER_REPO:latest

workflows:
  version: 2

  build_test:
    jobs:
      - checkout_code
      - unit_tests:
          requires:
            - checkout_code
      - build_binary:
          requires:
            - checkout_code
      - deploy_image:
          filters:
            branches:
              only: master
          requires:
            - unit_tests
            - build_binary
