version: 2
jobs:
  checkout_code:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/coreos/dex
    steps:
      - checkout
  install_ldap:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/coreos/dex
    steps:
      - run: sudo -E apt-get install -y --force-yes slapd time ldap-utils
      - run:
          name: Start LDAP
          command: sudo /etc/init.d/slapd stop
  unit_tests:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.4.12-alpine
        environment:
           POSTGRES_USER: root
           POSTGRES_DB: circle_test
    working_directory: /go/src/github.com/coreos/dex
    environment:
      TEST_RESULTS: /tmp/test-results
      DEX_POSTGRES_DATABASE: postgres
      DEX_POSTGRES_USER: postgres
      DEX_POSTGRES_HOST: localhost
      DEX_LDAP_TESTS: 1
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: go get -u github.com/golang/lint/golint
      - run: make testall

workflows:
  version: 2

  build_test:
    jobs:
      - checkout_code
      - install_ldap
      - unit_tests:
          requires:
            - checkout_code
            - install_ldap
